### ISSUE TITLE
How to implement `Create or update` functionality with provided steps

### ISSUE THREAD

**Issue by wouterroos** [LockTar/AzureAdApplicationManagement#11]
Hi, 

I'm looking into this extension to see if we can use it to provision Azure AD Application registrations in our release pipeline and I was wondering if it is possible to have a 'Create or update' that determines if an app registration already exists before setting its values. Is this possible using this extension?

Thanks in advance,

Regards,
Wouter

**Comment by LockTar** [comment]
Hi @wouterroos, good question. When I was testing my extension in a real example I came up with the same situation. The functionality is at this moment not really in the extension but it is possible. I was planning to do this in the next version.

But it is possible because I do this in my own pipeline as well. In order to do this, you have to add 4 tasks in your pipeline. 
First add a Get by Name task to determine if the application already exists. 
Than a Create task based on the first task outcome. 
Than an Update task to update everything.
And as last a Get task again for getting the updated values to use it in the rest of your pipeline. 

For every task you have to use the output variables and a custom run condition. 

I know it is a bit more work but I know it works. Or you have to wait for the update but I don't know when I have time. I'm now on holiday.

**Comment by wouterroos** [comment]
@LockTar Thanks for the quick response. I'm going to write a Task Group for my release definition for now following the steps you mentioned. If I have some time to spare in the near future I might try and write the PowerShell equivalent so we can have this behavior in a single step. 
Thanks for your help so far!

**Comment by LockTar** [comment]
@wouterroos I'm busy with this functionality. It is almost finished. Need some more testing and then I will publish the new minor version to the market place.

**Comment by LockTar** [comment]
@wouterroos, it's implemented. New version is available. Also added some other small enhancements.

**Comment by wouterroos** [comment]
@LockTar great, will check it out next week!

**Comment by wouterroos** [comment]
Hi @LockTar,

I'm currently testing the new version and it seems to work quite well. I'm however having some issues with supplying multiple ReplyUrl's based on a single variable. Is there any way to supply a list of reply url's using a single, environment specific variable? Also, the current output variable doesn't support having the '.' character, is there any way this can be added? A lot of config transform steps (especially appsettings.json) use a '.' to find nested values. I've seen some extensions that use something like 
`Write-Host "##vso[task.setvariable variable=$OutputParameterPrefix.ObjectId;]$($application.ObjectId)"` to write variables to the release.

Thanks in advance

**Comment by LockTar** [comment]
@wouterroos can you create new issues for these questions because I'm not sure what is related and other people find related topic easier. Also can you elaborate the question about '.' character in the output variable? Because I'm not sure which output variable you mean and in which task? thanks

**Comment by wouterroos** [comment]
@LockTar sure, see #13 and #14

**Comment by wouterroos** [comment]
@LockTar also see #15 for an additional feature request.
