### ISSUE TITLE
Support '.' character (and possibly others) in output variables

### ISSUE THREAD

**Issue by wouterroos** [LockTar/AzureAdApplicationManagement#13]
Hi,

Currently, the only possibility to get output (ClientId etc.) from the steps is to use the default 'Output Variables' provided by Azure DevOps (see image below).

![image](https://user-images.githubusercontent.com/5137829/47495880-98ab8f00-d855-11e8-8277-6fcfcb79bf7a.png)

However, this mechanism doesn't allow for any special characters (apart from '_') in the 'Reference name' field.

Some other steps I've used use another mechanism in their scripts that does allow this flexibility:

`Write-Host "##vso[task.setvariable variable=$Prefix.ObjectId;]$($application.ObjectId)" `

In which `$Prefix` would be a variable that can be defined in the step like:

![image](https://user-images.githubusercontent.com/5137829/47496029-05bf2480-d856-11e8-910f-ea5ff4623c33.png)

_example taken from: https://marketplace.visualstudio.com/items?itemName=keesschollaart.arm-outputs_

Is this something that could perhaps be added?

Thanks in advance,

Regards,
Wouter

**Comment by LockTar** [comment]
Hi @wouterroos,
Output variables is a default capability of Azure DevOps. So you have not much room to add things. I know which extension your referring to because I used it a lot in the past. Almost same capability is now supported in Arm template of Microsoft.

Back to your question.
The [output variable documentation](https://github.com/Microsoft/azure-pipelines-agent/blob/master/docs/preview/outputvariable.md) says what you can do as a developer.
So:
```json
"outputVariables": [{
    "name": "ObjectId",
    "description": "The ObjectId of the Azure AD Application"
}]
```
The system will prefix the name field with the Reference name.
So no control there.

**Comment by LockTar** [comment]
I will close the issue because no reply anymore. Reopen it if needed.
