### ISSUE TITLE
250 object limitation?

### ISSUE THREAD

**Issue by michaelrhyndress** [LockTar/AzureAdApplicationManagement#29]
Does this method of creating Azure AD apps with an underlying SPN transcend the 250 object limit defined in the service limitation [documentation](https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-service-limits-restrictions)?

> A non-admin user can create no more than 250 objects. Both active objects and deleted objects that are available to restore count toward this quota. Only deleted objects that were deleted fewer than 30 days ago are available to restore. Deleted objects that are no longer available to restore count toward this quota at a value of one-quarter for 30 days. Perhaps assign an administrator role to non-admin users who are likely to repeatedly exceed this quota in the course of their regular duties.

**Comment by LockTar** [comment]
As every answer, it depends. 
Good question because I've had this issue as well in the past. 

When you use this extension task, your "deploy service principal" (the parent that creates new child app registrations) needs to have the permissions specified in the [documentation](https://github.com/LockTar/AzureAdApplicationManagement/blob/master/README.md). Those permissions needs of course be granted by a Global administrator. 

At this point your parent deploy sp is just a normal user that can create new child app registrations. So at this point the answer to your question is no. The limit is than still 250. 

When you give the parent sp the Global Administrator role (confirmed by Microsoft AD team) the limitations is gone. PowerShell script (found old in email so maybe need to change it a bit) to give the role is:

```ps1
    Connect-AzureAD

    $mysp = Get-AzureADServicePrincipal -searchstring 'NAME OF SP'
    $mysp.ObjectId

    $myAADRole = Get-AzureADDirectoryRole | Where-Object {$_.displayName -eq 'Global Administrator'}
    $myAADRole.ObjectId

    Add-AzureADDirectoryRoleMember -ObjectId $myAADRole.ObjectId -RefObjectId $mysp.ObjectId
```
